print(".....A.....")
print("....*AA....")
print("...AAA*A...")
print("..A*AAAAA..")
print(".AAAAAA*AA.")
print("AA*AAAA*AAA")
print(".....B.....")
print("\n")
print("     A     ")
print("    *AA    ")
print("   A*AA*   ")
print("  A*AAA*A  ")
print(" A*AA*AA*A ")
print("AA*AA*AA*AA \n    ||")
print("\n")
print("      *     ")
print("     ***     ")
print("    *****    ")
print("   *******   ")
print("  Sarbatori  ")
print(" *fericite!*")
print("***PYTA14!*** \n     ||")
print("La multi ani!")

